groupware/src/main/java/com/mjc/groupware/approval/admin/service/AdminApprovalService.java
groupware/src/main/java/com/mjc/groupware/approval/user/service/UserApprovalService.java

approval admin/user service 클래스 생성 commit

[jji] approval admin/user service 클래스 생성 commit

---

groupware/src/main/java/com/mjc/groupware/home/comtroller/HomeController.java

[ysw] branch test commit

---

groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/admin/createApproval.html
groupware/src/main/resources/templates/include/layout.html
groupware/src/main/resources/templates/include/nav.html

[jji] 써머노트 적용 및 layout에 Js, jquery 추가 commit

[jji] 써머노트 적용 및 layout에 Js, jquery 추가 commit

---

groupware/src/main/java/com/mjc/groupware/home/comtroller/HomeController.java
groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java
groupware/src/main/java/com/mjc/groupware/plan/dto/PlanDto.java
groupware/src/main/java/com/mjc/groupware/plan/entity/Plan.java
groupware/src/main/java/com/mjc/groupware/plan/entity/PlanAlarm.java
groupware/src/main/java/com/mjc/groupware/plan/repository/PlanRepository.java
groupware/src/main/java/com/mjc/groupware/plan/service/PlanService.java
groupware/src/main/resources/templates/plan/calendar.html

[Psb] plan패키지 commit

---

groupware/src/main/java/com/mjc/groupware/LoggerAspect.java
groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalFormDto.java
groupware/src/main/java/com/mjc/groupware/approval/entity/ApprovalForm.java
groupware/src/main/java/com/mjc/groupware/approval/repository/ApprovalFormRepository.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/resources/logback-spring.xml
groupware/src/main/resources/templates/approval/admin/createApproval.html
groupware/src/main/resources/templates/include/layout.html

[jji] 결재 양식 생성 및 Logger 추가 commit

[jji] 결재 양식 생성 및 Logger 추가 commit

---

groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/controller/MeetingRoomController.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingRoomDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingRoomReservationDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingRoomReservationMappingDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingRoom.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingRoomReservation.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingRoomReservationMapping.java
groupware/src/main/java/com/mjc/groupware/member/dto/MemberDto.java
groupware/src/main/java/com/mjc/groupware/member/entity/Member.java
groupware/src/main/java/com/mjc/groupware/member/security/MemberDetails.java
groupware/src/main/java/com/mjc/groupware/member/security/MemberDetailsService.java
groupware/src/main/java/com/mjc/groupware/member/security/WebSecurityConfig.java
groupware/src/main/java/com/mjc/groupware/member/service/MemberService.java
groupware/src/main/resources/templates/include/nav.html
groupware/src/main/resources/templates/meetingRoom/adminMeetingRoomReservation.html
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[ysw] 회의실 관리(관리자), 회의실 예약(유저) 페이지 생성

[ysw] 회의실 관리(관리자), 회의실 예약(유저) 페이지 생성

---

groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/admin/createApproval.html

[jji] 페이지 기본 구성 추가 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/admin/createApprovalForm.html
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/receiveApproval.html

[jji] 전자 결재 시스템 페이지 기본 화면 구현 commit

[jji] 전자 결재 시스템 페이지 기본 화면 구현 commit

---

groupware/src/main/java/com/mjc/groupware/member/controller/MemberController.java
groupware/src/main/java/com/mjc/groupware/member/entity/Member.java
groupware/src/main/java/com/mjc/groupware/member/service/MemberService.java
groupware/src/main/java/com/mjc/groupware/pos/controller/PosController.java
groupware/src/main/java/com/mjc/groupware/pos/dto/PosDto.java
groupware/src/main/java/com/mjc/groupware/pos/dto/PosOrderDto.java
groupware/src/main/java/com/mjc/groupware/pos/entity/Pos.java
groupware/src/main/java/com/mjc/groupware/pos/service/PosService.java
groupware/src/main/resources/templates/dept/create.html
groupware/src/main/resources/templates/include/nav.html
groupware/src/main/resources/templates/member/create.html
groupware/src/main/resources/templates/pos/create.html

[cjs] Pull Request :: cjs -> dev

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalFormDto.java
groupware/src/main/java/com/mjc/groupware/approval/entity/ApprovalForm.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/resources/static/css/jji.css
groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/admin/createApprovalForm.html
groupware/src/main/resources/templates/approval/admin/updateApprovalForm.html
groupware/src/main/resources/templates/approval/user/createApproval.html

[jji] 관리자 기능 중간 commit

---

groupware/src/main/resources/templates/plan/calendar.html

[psb] calendar 커밋

---

groupware/src/main/java/com/mjc/groupware/home/comtroller/HomeController.java
groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/include/nav.html
groupware/src/main/resources/templates/plan/calendar.html

[psb] 일정 화면 수정 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/member/dto/MemberDto.java
groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/admin/createApprovalForm.html
groupware/src/main/resources/templates/approval/admin/updateApprovalForm.html
groupware/src/main/resources/templates/approval/user/approval.html
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/receiveApproval.html

[jji] 결재작성 양식 생성 commit

---

groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java
groupware/src/main/java/com/mjc/groupware/plan/dto/PlanDto.java
groupware/src/main/java/com/mjc/groupware/plan/entity/Plan.java
groupware/src/main/java/com/mjc/groupware/plan/repository/PlanRepository.java
groupware/src/main/java/com/mjc/groupware/plan/service/PlanService.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/plan/calendar.html

[psb]일정추가,상세 modal분리 commit

---

groupware/src/main/java/com/mjc/groupware/plan/dto/PlanDto.java
groupware/src/main/java/com/mjc/groupware/plan/entity/Plan.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/plan/calendar.html

[psb] 일정추가시 데이터베이스에 저장(연결) commit

[psb] 일정추가시 데이터베이스에 저장(연결) commit

---

groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/Service/MeetingRoomService.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/controller/MeetingRoomController.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingRoomTimeDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingTimeMappingDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingRoomReservation.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingTime.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingTimeMapping.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/repository/MeetingTimeRepository.java
groupware/src/main/resources/static/js/custom/meetingRoomCalendar.js
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[ysw] 사용자 - 예약 캘린더 수정 및 사용자 - 회의실 예약 기능 구현 중 commit

[ysw] 사용자 - 예약 캘린더 수정 및 사용자 - 회의실 예약 기능 구현 중 commit

---

groupware/src/main/resources/static/js/ysw/jstree.js
groupware/src/main/resources/templates/include/layout.html
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[ysw] 조직도 적용

---

groupware/src/main/resources/static/js/jji/jstree.js
groupware/src/main/resources/templates/approval/user/createApproval.html

[jji] 결재 라인 선택 기능 구현 commit

---

groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/Service/MeetingRoomService.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/controller/MeetingRoomController.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingRoomReservationDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingRoomReservation.java
groupware/src/main/resources/static/js/custom/meetingRoomCalendar.js
groupware/src/main/resources/static/js/ysw/jstree.js
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[YSW] 회의실 예약 인원 선택 반영

---

groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java
groupware/src/main/java/com/mjc/groupware/plan/service/PlanService.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/plan/calendar.html

[psb] 캘린더 목록출력 commit

---

groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/Service/MeetingRoomService.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/controller/MeetingRoomController.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingRoomDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingRoomReservationDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingRoomReservationMappingDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingRoom.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingRoomReservation.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingRoomReservationMapping.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/repository/MeetingRoomRepository.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/repository/MeetingRoomReservationMappingRepository.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/repository/MeetingRoomReservationRepository.java
groupware/src/main/resources/static/js/custom/meetingRoomCalendar.js
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[ysw] 회의실 예약 추가 기능

---

groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java
groupware/src/main/java/com/mjc/groupware/plan/dto/PlanDto.java
groupware/src/main/java/com/mjc/groupware/plan/entity/Plan.java
groupware/src/main/java/com/mjc/groupware/plan/repository/PlanRepository.java
groupware/src/main/java/com/mjc/groupware/plan/service/PlanService.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/plan/calendar.html

[psb] 캘린더 화면에 db정보 뿌려주기

---

groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/resources/templates/approval/user/receiveApproval.html

[jji] 받은 결재 목록 조회 commit

---

groupware/src/main/java/com/mjc/groupware/plan/dto/PlanDto.java

[psb] pull request commit

---

groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/Service/MeetingRoomService.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/controller/MeetingRoomController.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/dto/MeetingRoomReservationDto.java
groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/entity/MeetingRoomReservation.java
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[ysw] 사용자- 내 이용 내역 조회 + 조회 필터 추가 , 회의실 예약 및 조회 세부 조건 추가

[ysw] 사용자- 내 이용 내역 조회 + 조회 필터 추가 , 회의실 예약 및 조회 세부 조건 추가

---

groupware/src/main/java/com/mjc/groupware/member/controller/MemberController.java
groupware/src/main/java/com/mjc/groupware/member/dto/MemberSearchDto.java
groupware/src/main/java/com/mjc/groupware/member/dto/StatusDto.java
groupware/src/main/java/com/mjc/groupware/member/repository/MemberRepository.java
groupware/src/main/java/com/mjc/groupware/member/service/MemberService.java
groupware/src/main/java/com/mjc/groupware/member/specification/MemberSpecification.java
groupware/src/main/resources/static/css/cjs/dept_create.css
groupware/src/main/resources/static/css/cjs/member_list.css
groupware/src/main/resources/templates/member/list.html

[cjs] 전체 사원 정보 조회 및 수정 // 검색까진 되고, 페이징과 정렬 작업해야함

[cjs] 전체 사원 정보 조회 및 수정 // 검색까진 되고, 페이징과 정렬 작업해야함

---

groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/controller/MeetingRoomController.java
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[ysw] 사용자 - 회의실 예약 시간 조건 추가

---

groupware/src/main/java/com/mjc/groupware/approval/mybatis/vo/ApprovalVo.java
groupware/src/main/resources/mybatis/mappers/approval-mapper.xml
groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/user/approval.html
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/receiveApproval.html
groupware/src/main/resources/templates/approval/user/receiveApprovalDetail.html

[jji] 결재라인 모달창 수정, 관리자&사원 결재작성 페이지 자동 버튼 클릭 및 결재상세페이지 수정 중 commit

[jji] 결재라인 모달창 수정, 관리자&사원 결재작성 페이지 자동 버튼 클릭 및 결재상세페이지 수정 중 commit

---

groupware/src/main/java/com/mjc/groupware/meetingRoomReservation/Service/MeetingRoomService.java
groupware/src/main/resources/templates/meetingRoom/adminMeetingReservation.html
groupware/src/main/resources/templates/meetingRoom/adminMeetingRoomSelect.html

[ysw] 회의실 예약 기능 구현 완료 

---

groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[ysw] 회의실 최종 commit

---

groupware/build.gradle
groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMappingDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatRoomDto.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatMapping.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatMsg.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatRoom.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatRoomRepository.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatRoomService.java
groupware/src/main/java/com/mjc/groupware/chat/specification/ChatRoomSpecification.java
groupware/src/main/java/com/mjc/groupware/chat/websocket/BasicWebSocketHandler.java
groupware/src/main/java/com/mjc/groupware/chat/websocket/ChatWebSocketHandler.java
groupware/src/main/java/com/mjc/groupware/chat/websocket/WebSocketConfig.java
groupware/src/main/resources/templates/chat/chat.html

[ysw] 웹소캣 서버 연결, 환경설정 진행 중

---

groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalDto.java
groupware/src/main/java/com/mjc/groupware/approval/entity/Approval.java
groupware/src/main/java/com/mjc/groupware/approval/mybatis/vo/ApprovalVo.java
groupware/src/main/resources/mybatis/mappers/approval-mapper.xml
groupware/src/main/resources/static/css/jji.css
groupware/src/main/resources/templates/approval/user/approval.html
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/receiveApproval.html
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[jji] 회의실 css 수정 및 결재 페이지 수정 중 commit

[jji] 회의실 css 수정 및 결재 페이지 수정 중 commit

---

groupware/src/main/java/com/mjc/groupware/board/controller/BoardController.java
groupware/src/main/java/com/mjc/groupware/board/repository/BoardRepository.java
groupware/src/main/java/com/mjc/groupware/board/service/BoardAttachService.java
groupware/src/main/java/com/mjc/groupware/board/service/BoardService.java
groupware/src/main/java/com/mjc/groupware/member/security/WebSecurityConfig.java
groupware/src/main/java/com/mjc/groupware/reply/controller/ReplyController.java
groupware/src/main/java/com/mjc/groupware/reply/dto/ReplyDto.java
groupware/src/main/java/com/mjc/groupware/reply/entity/Reply.java
groupware/src/main/java/com/mjc/groupware/reply/repository/ReplyRepository.java
groupware/src/main/java/com/mjc/groupware/reply/service/ReplyService.java
groupware/src/main/resources/templates/board/create.html
groupware/src/main/resources/templates/board/detail.html
groupware/src/main/resources/templates/board/list.html
groupware/src/main/resources/templates/board/update.html

게시판 css 조금 수정 완료
댓글/대댓글 -> 댓글 기능은 일단 완료 했고, css 부분적인거 아직 미완성 / 댓글이 끝나면 대댓글 할 생각입니다.

[kdy] 게시판 css 및 댓글만 기능 추가

---

groupware/src/main/resources/static/css/kdy.css
groupware/src/main/resources/templates/board/detail.html
groupware/src/main/resources/templates/board/list.html

게시글 작성
게시글 목록
정현님 CSS 보고 수정했습니다.

[kdy] 게시글 css 수정

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatRoomDto.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatMapping.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatMsg.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatRoom.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatRoomRepository.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatRoomService.java
groupware/src/main/java/com/mjc/groupware/chat/specification/ChatRoomSpecification.java
groupware/src/main/resources/static/js/ysw/chat.js
groupware/src/main/resources/templates/chat/chat.html

[ysw] 채팅 html 구성 완료, 채팅방 목록 조회 기능 추가

[ysw] 채팅 html 구성 완료, 채팅방 목록 조회 기능 추가

---

groupware/src/main/resources/templates/chat/chat.html

[ysw] chat.html 채팅방 추가 버튼

---

groupware/src/main/resources/static/js/custom/calendar.js

[psb] 일정타입 필터링 commit2

---

groupware/src/main/resources/static/js/ysw/jstree.js
groupware/src/main/resources/templates/chat/chat.html
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[ysw] 회의실 예약, 채팅 html 조직도 css 수정

[ysw] 회의실 예약, 채팅 html 조직도 css 수정

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprAgreementerDto.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprApproverDto.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprReferencerDto.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalDto.java
groupware/src/main/java/com/mjc/groupware/approval/entity/ApprAgreementer.java
groupware/src/main/java/com/mjc/groupware/approval/entity/ApprApprover.java
groupware/src/main/java/com/mjc/groupware/approval/entity/Approval.java
groupware/src/main/java/com/mjc/groupware/approval/repository/ApprAgreementerRepository.java
groupware/src/main/java/com/mjc/groupware/approval/repository/ApprApproverRepository.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/java/com/mjc/groupware/approval/vo/ApprAgreementerVo.java
groupware/src/main/java/com/mjc/groupware/approval/vo/ApprApproverVo.java
groupware/src/main/resources/static/css/jji.css
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/receiveApproval.html
groupware/src/main/resources/templates/approval/user/receiveApprovalDetail.html

[jji] 결재라인 중복 등록 방지 및 결재자 합의자 순서 결재기능 commit

[jji] 결재라인 중복 등록 방지 및 결재자 합의자 순서 결재기능 commit

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/AccommodationDto.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/entity/Accommodation.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/repository/AccommodationRepository.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationService.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/accommodation/accommodation.html
groupware/src/main/resources/templates/plan/calendar.html

[psb] 구글 공휴일 api 연동 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/PageDto.java
groupware/src/main/java/com/mjc/groupware/approval/dto/SearchDto.java
groupware/src/main/java/com/mjc/groupware/approval/mybatis/mapper/ApprovalMapper.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/resources/mybatis/mappers/approval-mapper.xml
groupware/src/main/resources/templates/approval/user/receiveApproval.html

[jji] 받은 문서함(결재) 검색 기능 구현 commit

[jji] 받은 문서함(결재) 검색 기능 구현 commit

---

groupware/src/main/resources/static/assets/js/apps/calendar-init.js
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/plan/calendar.html

[psb] 캘린더명 타입별 클릭시 변경되도록 하는 코드 commit

[psb] 캘린더명 타입별 클릭시 변경되도록 하는 코드 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/PageDto.java
groupware/src/main/java/com/mjc/groupware/approval/dto/SearchDto.java
groupware/src/main/java/com/mjc/groupware/approval/repository/ApprovalRepository.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/java/com/mjc/groupware/approval/specification/ApprovalSpecification.java
groupware/src/main/java/com/mjc/groupware/member/dto/MemberDto.java
groupware/src/main/resources/templates/approval/user/approval.html

[jji] 보낸 문서함(보낸 결재) 검색, 필터, 페이징 구현 commit

[jji] 보낸 문서함(보낸 결재) 검색, 필터, 페이징 구현 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/java/com/mjc/groupware/approval/vo/ApprApproverVo.java
groupware/src/main/resources/mybatis/mappers/approval-mapper.xml
groupware/src/main/resources/templates/approval/user/approval.html
groupware/src/main/resources/templates/approval/user/receiveApproval.html

[jji] 받은 문서함(받은 결재) 필터(최신순, 오래된순) 정렬 구현 및 검색기록 남기기 commit

[jji] 받은 문서함(받은 결재) 필터(최신순, 오래된순) 정렬 구현 및 검색기록 남기기 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/sendApproval.html
groupware/src/main/resources/templates/approval/user/sendApprovalDetail.html

[jji] 보낸 결재 상세페이지 및 커스텀 class 수정 commit

[jji] 보낸 결재 상세페이지 및 커스텀 class 수정 commit

---

groupware/src/main/java/com/mjc/groupware/reply/dto/ReplyDto.java
groupware/src/main/java/com/mjc/groupware/reply/entity/Reply.java
groupware/src/main/java/com/mjc/groupware/reply/service/ReplyService.java
groupware/src/main/resources/templates/board/detail.html

정현님꺼 보고 이제 상세 페이지 html 수정했습니다.

[kdy] 게시글 상세 페이지 html 수정

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatMsg.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatMsgRepository.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatMsgService.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatRoomService.java
groupware/src/main/java/com/mjc/groupware/chat/specification/ChatMsgSpecification.java
groupware/src/main/java/com/mjc/groupware/member/entity/Member.java
groupware/src/main/resources/templates/chat/chat.html

[ysw] 1:1 채팅 화면 구현 중

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/PageDto.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/resources/templates/approval/user/receiveApproval.html
groupware/src/main/resources/templates/approval/user/sendApproval.html

[jji] 받은 문서함 번호 순서 변경 commit

---

groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/plan/calendar.html

1.일정 등록 시 사용자 부서명을 일정 바에 출력
2.일정색상 안내 부분에 커서 포인터 설정
3.일정색상 안내 영역 정렬 정비

[psb] 일정바앞 부서명 넣어주는 코드,일정색상 안내영역 수정 commit

---

groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java
groupware/src/main/java/com/mjc/groupware/plan/dto/PlanDto.java
groupware/src/main/java/com/mjc/groupware/plan/service/PlanService.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/plan/calendar.html

[psb] 일정을 수정/삭제할 수 있는 범위 설정 commit

[psb] 일정을 수정/삭제할 수 있는 범위 설정 commit

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMemberInfoDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatRoomDto.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatRoom.java
groupware/src/main/resources/templates/chat/chat.html

[ysw] 채팅방 참여 인원 불러오기 진행중

---

groupware/src/main/resources/templates/chat/chat.html

[ysw] 사용자 이미지 반영

---

groupware/src/main/resources/static/js/custom/calendar.js

[psb] 부서일정에만 일정앞에 부서명넣음 commit

[psb] 부서일정에만 일정앞에 부서명넣음 commit

---

groupware/src/main/resources/templates/approval/user/receiveApprovalDetail.html
groupware/src/main/resources/templates/approval/user/sendApprovalDetail.html

[jji] 합의자 전자서명 오류 수정 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java

[jji] commit test

---

groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/plan/calendar.html

[psb] 수정기록 남기는 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/SearchDto.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/java/com/mjc/groupware/approval/specification/ApprovalSpecification.java
groupware/src/main/resources/static/css/jji.css
groupware/src/main/resources/static/js/jji/jstree.js
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/sendApproval.html

[jji] 보낸 결재함 상태별 필터 적용 기능 구현 및 결재라인 선택 시 체크박스 disable 처리 구현 commit

[jji] 보낸 결재함 상태별 필터 적용 기능 구현 및 결재라인 선택 시 체크박스 disable 처리 구현 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/PageDto.java
groupware/src/main/java/com/mjc/groupware/approval/mybatis/mapper/ApprovalMapper.java
groupware/src/main/java/com/mjc/groupware/approval/mybatis/vo/ApprovalStatusVo.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/resources/mybatis/mappers/approval-mapper.xml
groupware/src/main/resources/templates/approval/user/receiveApproval.html

[jji] 받은 문서함(받은 결재) 결재자, 합의자, 참조자에 따른 필터링(검색, 정렬, 페이징) 기능 구현 commit

[jji] 받은 문서함(받은 결재) 결재자, 합의자, 참조자에 따른 필터링(검색, 정렬, 페이징) 기능 구현 commit

---

groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalDto.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalFormDto.java
groupware/src/main/java/com/mjc/groupware/approval/entity/ApprovalForm.java
groupware/src/main/java/com/mjc/groupware/member/dto/MemberDto.java
groupware/src/main/java/com/mjc/groupware/member/entity/Member.java
groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/user/createApproval.html

[jji] 연차 신청서 구현 중 commit

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatMsg.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatMsgRepository.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatMsgService.java
groupware/src/main/java/com/mjc/groupware/chat/websocket/WebSocketConfig.java
groupware/src/main/resources/templates/chat/chat.html

[ysw] 1:1 채팅 구현 중 commit

---

groupware/src/main/java/com/mjc/groupware/board/controller/BoardController.java
groupware/src/main/java/com/mjc/groupware/board/service/BoardService.java
groupware/src/main/resources/templates/board/detail.html
groupware/src/main/resources/templates/board/list.html

조회수 즉각 반영 완료
자유게시판 목록 페이지에서 수정일 제거
답글달기 버튼 형식이 아니라 글씨 형식으로 바꿈

[kdy] 게시판/댓글/대댓글 수정 commit

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/resources/templates/chat/chat.html

[ysw] stomp 연결 , 실시간 채팅 구현 중

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalDto.java
groupware/src/main/java/com/mjc/groupware/approval/entity/Approval.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/resources/templates/approval/admin/createApprovalForm.html
groupware/src/main/resources/templates/approval/admin/updateApprovalForm.html
groupware/src/main/resources/templates/approval/user/createApproval.html

[jji] [관리자] 결재양식 생성 및 수정 페이지 toast Ui editor 적용 완료 commit

[jji] [관리자] 결재양식 생성 및 수정 페이지 toast Ui editor 적용 완료 commit

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationController.java
groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java
groupware/src/main/java/com/mjc/groupware/plan/dto/PlanDto.java
groupware/src/main/java/com/mjc/groupware/plan/dto/PlanLogDto.java
groupware/src/main/java/com/mjc/groupware/plan/entity/Plan.java
groupware/src/main/java/com/mjc/groupware/plan/entity/PlanLog.java
groupware/src/main/java/com/mjc/groupware/plan/repository/PlanRepository.java
groupware/src/main/java/com/mjc/groupware/plan/service/PlanService.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/include/nav.html
groupware/src/main/resources/templates/plan/calendar.html

[psb] 삭제YN변경,planLog 코드 commit

[psb] 삭제YN변경,planLog 코드 commit

---

groupware/src/main/java/com/mjc/groupware/reply/controller/ReplyController.java
groupware/src/main/java/com/mjc/groupware/reply/dto/ReplyDto.java
groupware/src/main/java/com/mjc/groupware/reply/repository/ReplyRepository.java
groupware/src/main/java/com/mjc/groupware/reply/service/ReplyService.java
groupware/src/main/resources/static/css/kdy.css
groupware/src/main/resources/templates/board/detail.html

[kdy] 댓글/대댓글 부분 수정
답글달기 클릭해서 답글을 등록하면 답글 x개 이런식(>(폈다),<(접었다)) 기능 추가
댓글/대댓글 수정할때 시간은 등록일로 고정되고, 수정이되면 (수정됨) -> 뒤로가기하면 (수정됨)이 그대로 남아있음
안되는 기능 구현중
댓글창이 아직도 상세까지 올라가는현상
대댓글창이 대댓글을 등록하면 사라지지 않는 현상
사용자가 프로필 이미지를 변경하면 반영 / 아무것도 없다면 기본 프로필 이미지 반영 구현중

[kdy] 댓글/대댓글 부분 수정 commit

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatMsgService.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatRoomService.java
groupware/src/main/resources/templates/chat/chat.html

[ysw] 1:1채팅 구현, db 저장 완료, 채팅방 추가 제목 오류 수정

[ysw] 1:1채팅 구현, db 저장 완료, 채팅방 추가 제목 오류 수정

---

groupware/src/main/java/com/mjc/groupware/chat/entity/ChatRoom.java
groupware/src/main/resources/templates/chat/chat.html

[ysw] 채팅방 entity 수정

---

groupware/src/main/java/com/mjc/groupware/reply/dto/ReplyDto.java
groupware/src/main/java/com/mjc/groupware/reply/entity/Reply.java
groupware/src/main/resources/templates/board/detail.html

댓글창을 아래에 고정, 대댓글은 대댓글안에 등록창 고정
사용자가 프로필 이미지를 변경하여 반영 / 아무것도 없다면 기본 이미지 반영
댓글/대댓글 작성자 등록일 수정을 하게 되면 등록일 그대로(수정됨)이라는 문구가 저장됨

[kdy] 댓글/대댓글 기능 수정 commit

---

groupware/src/main/java/com/mjc/groupware/vote/controller/VoteController.java
groupware/src/main/java/com/mjc/groupware/vote/dto/VoteDto.java
groupware/src/main/java/com/mjc/groupware/vote/entity/Vote.java
groupware/src/main/java/com/mjc/groupware/vote/repository/VoteRepository.java
groupware/src/main/java/com/mjc/groupware/vote/service/VoteService.java
groupware/src/main/java/com/mjc/groupware/vote/specification/VoteSpecification.java
groupware/src/main/resources/static/css/kdy.css
groupware/src/main/resources/templates/board/create.html
groupware/src/main/resources/templates/board/detail.html
groupware/src/main/resources/templates/board/list.html
groupware/src/main/resources/templates/board/update.html

댓글/대댓글 글자색 변경(답글x개 글자색 변경)
답글 달기 텍스트 위 아래 변경 완료
댓글창 크기 조절, 댓글/대댓글 바깥쪽 div로 묶어줌
답글달기는 밑줄처럼 보이게 하는게 좋다하셔서 예전처럼 바꿈
자유게시판 목록에서 x표시 초기화 없앰
답글x개랑 밑에 대댓글창이랑 여백을 띄어줌
댓글창은 div 박스 아래에 배치될수있게 생성했으면 좋겠다고 하셔서 바꿈

[kdy] 댓글/대댓글(게시판도 포함) html,css 수정

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatMsg.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatMappingrepository.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatMsgService.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatRoomService.java
groupware/src/main/java/com/mjc/groupware/chat/specification/ChatMappingSpecification.java
groupware/src/main/resources/static/js/ysw/jstree.js
groupware/src/main/resources/templates/chat/chat.html
groupware/src/main/resources/templates/meetingRoom/meetingRoomReservation.html

[ysw] 채팅 나가기 구현 + 사용자 나감 메세지 표시

[ysw] 채팅 나가기 구현 + 사용자 나감 메세지 표시

---

groupware/src/main/resources/templates/chat/chat.html

[ysw] 채팅방 인원추가 구현 중 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalDto.java
groupware/src/main/java/com/mjc/groupware/approval/entity/Approval.java
groupware/src/main/java/com/mjc/groupware/approval/repository/ApprovalRepository.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/java/com/mjc/groupware/approval/specification/ApprovalSpecification.java
groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/user/receiveApprovalDetail.html
groupware/src/main/resources/templates/approval/user/sendApprovalDetail.html

[jji] 회수 처리 및 회수버튼 숨김 진행중 commit

[jji] 회수 처리 및 회수버튼 숨김 진행중 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalDto.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/java/com/mjc/groupware/plan/dto/PlanDto.java
groupware/src/main/java/com/mjc/groupware/plan/entity/Plan.java
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/receiveApprovalDetail.html
groupware/src/main/resources/templates/approval/user/retryApproval.html
groupware/src/main/resources/templates/approval/user/sendApprovalDetail.html

[jji] 재기안 기능 구현 및 결재회수 기능 마무리 commit

[jji] 재기안 기능 구현 및 결재회수 기능 마무리 commit

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatAlarmDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatRoomReadDto.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatAlarm.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatRoomRead.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatAlarmRepository.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatMsgRepository.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatRoomReadRepository.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatAlarmService.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatMsgService.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatRoomService.java
groupware/src/main/java/com/mjc/groupware/chat/specification/ChatRoomReadSpecification.java
groupware/src/main/java/com/mjc/groupware/chat/specification/ChatRoomSpecification.java
groupware/src/main/resources/static/css/ysw.css
groupware/src/main/resources/templates/chat/chat.html
groupware/src/main/resources/templates/include/layout.html

[ysw] 채팅방 목록, 마지막 메세지 실시간 반영+안 읽은 메세지 개수 실시간 반영+ 알림 기능 구현 중

[ysw] 채팅방 목록, 마지막 메세지 실시간 반영+안 읽은 메세지 개수 실시간 반영+ 알림 기능 구현 중 

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/session/ChatSessionTracker.java
groupware/src/main/java/com/mjc/groupware/chat/session/SessionRegistry.java
groupware/src/main/resources/templates/chat/chat.html
groupware/src/main/resources/templates/include/layout.html

[ysw] 채팅방 안읽음 뱃지 오류 해결 

---

groupware/src/main/resources/static/css/kdy.css
groupware/src/main/resources/templates/board/create.html
groupware/src/main/resources/templates/board/detail.html
groupware/src/main/resources/templates/board/list.html

투표 기능에서 input 바깥쪽 -(항목제거) css 수정(alert창 추가)
페이지 제목 수정

[kdy] 부분 수정 완료

---

groupware/src/main/java/com/mjc/groupware/approval/dto/PageDto.java
groupware/src/main/java/com/mjc/groupware/attendance/controller/AttendanceController.java
groupware/src/main/java/com/mjc/groupware/attendance/dto/AttendPageDto.java
groupware/src/main/java/com/mjc/groupware/attendance/dto/SearchDto.java
groupware/src/main/java/com/mjc/groupware/attendance/repository/AttendanceRepository.java
groupware/src/main/java/com/mjc/groupware/attendance/service/AttendanceService.java
groupware/src/main/java/com/mjc/groupware/attendance/specification/AttendanceSpecification.java
groupware/src/main/resources/templates/attendance/user/attendanceInfo.html

[jji] 근무 이력 테이블 페이징 처리 진행중 commit

[jji] 근무 이력 테이블 페이징 처리 진행중 commit

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationAdminController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/AccommodationInfoDto.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationService.java
groupware/src/main/resources/static/css/psb.css
groupware/src/main/resources/templates/accommodation/adminHome.html
groupware/src/main/resources/templates/accommodation/adminUpdate.html
groupware/src/main/resources/templates/accommodation/detail.html

[psb] 필드,파일경로 오류 수정 commit

---

groupware/src/main/java/com/mjc/groupware/attendance/controller/AttendanceController.java
groupware/src/main/java/com/mjc/groupware/attendance/dto/SearchDto.java
groupware/src/main/java/com/mjc/groupware/attendance/service/AttendanceService.java
groupware/src/main/java/com/mjc/groupware/attendance/specification/AttendanceSpecification.java
groupware/src/main/resources/templates/approval/user/sendApproval.html
groupware/src/main/resources/templates/attendance/user/attendanceInfo.html
groupware/src/main/resources/templates/attendance/user/attendanceLog.html

[jji] 나의 근무 이력 페이지 필터, 날짜 검색, 페이징 처리 구현 commit

[jji] 나의 근무 이력 페이지 필터, 날짜 검색, 페이징 처리 구현 commit

---

groupware/src/main/java/com/mjc/groupware/attendance/controller/AttendanceController.java
groupware/src/main/java/com/mjc/groupware/attendance/dto/MemberAttendanceDto.java
groupware/src/main/java/com/mjc/groupware/attendance/repository/AttendanceRepository.java
groupware/src/main/java/com/mjc/groupware/attendance/service/AttendanceService.java
groupware/src/main/java/com/mjc/groupware/member/dto/MemberSearchDto.java
groupware/src/main/resources/static/js/jji/annual/jstree.js
groupware/src/main/resources/templates/attendance/admin/annualLeaveManagement.html
groupware/src/main/resources/templates/attendance/admin/attendanceManagement.html
groupware/src/main/resources/templates/attendance/user/attendanceLog.html

[jji] 근태 관리 페이지 데이터 출력 commit

---

groupware/src/main/java/com/mjc/groupware/board/controller/BoardController.java
groupware/src/main/java/com/mjc/groupware/reply/controller/ReplyController.java
groupware/src/main/java/com/mjc/groupware/reply/dto/ReplyDto.java
groupware/src/main/java/com/mjc/groupware/reply/repository/ReplyRepository.java
groupware/src/main/java/com/mjc/groupware/reply/service/ReplyService.java
groupware/src/main/java/com/mjc/groupware/vote/controller/VoteController.java
groupware/src/main/java/com/mjc/groupware/vote/dto/VoteResultDto.java
groupware/src/main/java/com/mjc/groupware/vote/repository/VoteResultRepository.java
groupware/src/main/java/com/mjc/groupware/vote/service/VoteService.java
groupware/src/main/resources/static/css/kdy.css
groupware/src/main/resources/templates/board/detail.html

사용자가 한번 투표를 하면 투표하기 버튼이 투표한 후 투표 불가 버튼이 생성되고, 투표 마감되었습니다 실시간 반영
새로고침해도 투표 마감되었습니다가 날아가지 않고 남아있음

[kdy] 선생님 피드백 부분 수정

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatAlarmDto.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatAlarmService.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatRoomService.java
groupware/src/main/resources/static/css/alarm.css
groupware/src/main/resources/templates/chat/chat.html
groupware/src/main/resources/templates/include/layout.html

[ysw] 채팅방 나가기 버튼 클릭 시 참여자 정보 실시간 반영 + 알림 기능 구현 중

[ysw] 채팅방 나가기 버튼 클릭 시 참여자 정보 실시간 반영 + 알림 기능 구현 중

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/attendance/controller/AttendanceController.java
groupware/src/main/java/com/mjc/groupware/member/dto/MemberSearchDto.java
groupware/src/main/java/com/mjc/groupware/member/service/MemberService.java
groupware/src/main/java/com/mjc/groupware/plan/repository/PlanRepository.java
groupware/src/main/java/com/mjc/groupware/plan/service/PlanService.java
groupware/src/main/resources/templates/attendance/admin/annualLeaveManagement.html
groupware/src/main/resources/templates/attendance/admin/attendanceManagement.html

[jji] 근태 관리 및 정보 구현 중

---

groupware/src/main/resources/templates/accommodation/detail.html
groupware/src/main/resources/templates/accommodation/list.html

1. 체크인,체크아웃 유효성 검사
- 오늘날짜 설정해서 과거날짜 선택 안되게 함
- 체크인 날짜변경시 체크아웃 최소날짜 조정되게함
- 체크인,체크아웃 입력안되면 등록안되고 alert창 뜨게함
3. 방갯수,인원수 숫자만 입력가능하게 설정(입력값 비어있으면 기본값 1로 설정)
4. 방갯수,인원수 각 50으로 최대값 설정(인원수와 방갯수가 최대값에 도달하면 증가버튼 비활성화되게함)

[psb] 예약등록부분 수정코드 commit

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationAdminController.java
groupware/src/main/resources/templates/accommodation/adminCreate.html
groupware/src/main/resources/templates/accommodation/adminUpdate.html

숙소등록시 첨부파일 오류 수정
1. 이미지 미리보기
- 첨부파일 공간에 등록한 이미지 넣기 
- 수정시 이미지 클릭해서 이미지 변경 가능하게
- 새이미지 등록시 첨부파일창 두번뜨는 오류 수정

[psb] 등록시 첨부파일 오류 수정 commit

---

groupware/src/main/java/com/mjc/groupware/board/controller/BoardController.java
groupware/src/main/java/com/mjc/groupware/board/service/BoardAttachService.java
groupware/src/main/java/com/mjc/groupware/vote/controller/VoteController.java
groupware/src/main/java/com/mjc/groupware/vote/service/VoteService.java
groupware/src/main/resources/static/css/kdy.css
groupware/src/main/resources/templates/board/detail.html

게시글 작성 일반글(고정글) 투표 추가없이 게시글 작성하는거 확인 수정 완료
게시글 작성 일반글 투표 추가를 하여 게시글 작성하는거 확인 수정 완료
파일 첨부에서 코드를 보니까 형식이 5개만 설정되어있어서 10개 더 추가해서 15개 형식 추가해줌
(예시:css,sql)파일들이 첨부파일에 넣어도 들어가지가 않아서 형식을 BoardAttachService에 더 추가해주니까 파일첨부가 됨

[kdy] 게시글 작성에서 일반글(고정글) 투표 추가 없이 게시글 작성 수정 완료/첨부파일 형식 5개에서 15개로 추가

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatAttachController.java
groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatAttachDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatAttach.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatAttachRepository.java
groupware/src/main/java/com/mjc/groupware/chat/repository/ChatMsgRepository.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatAttachService.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatMsgService.java
groupware/src/main/resources/static/css/ysw.css
groupware/src/main/resources/templates/chat/chat.html

[ysw] 채팅방 이미지, 파일 실시간 전송 및 다운로드 가능 + 채팅방 기존의 이미지, 파일 조회 진행 중

[ysw] 채팅방 이미지, 파일 실시간 전송 및 다운로드 가능 + 채팅방 기존의 이미지, 파일 조회 진행 중

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationReservationService.java
groupware/src/main/resources/templates/accommodation/adminList.html
groupware/src/main/resources/templates/accommodation/list.html

관리자가 승인(반려) 상태 변경하면 사용자 목록에 상태변경되고 예약취소 버튼을 결제하기 버튼으로 변경되게함
승인시 - 결제버튼
반려시 - 예약취소 버튼
대기시 - 예약취소 버튼

[psb] 승인,반려 상태 적용 완료 commit

---

groupware/src/main/java/com/mjc/groupware/attendance/controller/AttendanceController.java
groupware/src/main/java/com/mjc/groupware/attendance/dto/AttendanceDto.java
groupware/src/main/java/com/mjc/groupware/attendance/service/AttendanceService.java
groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/user/receiveApprovalDetail.html
groupware/src/main/resources/templates/approval/user/sendApprovalDetail.html
groupware/src/main/resources/templates/attendance/admin/attendanceManagement.html
groupware/src/main/resources/templates/attendance/user/attendanceInfo.html

[jji] 관리자 - 사원 근태 기록 수정 및 전자결재 결재양식 css 수정 commit

[jji] 관리자 - 사원 근태 기록 수정 및 전자결재 결재양식 css 수정 commit

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationReservationController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationReservationService.java
groupware/src/main/resources/templates/accommodation/adminList.html
groupware/src/main/resources/templates/accommodation/list.html

Ps[psb] 승인,반려,대기 commit

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationReservationController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/AccommodationReservationDto.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/entity/AccommodationReservation.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationAttachService.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationReservationService.java
groupware/src/main/resources/templates/accommodation/adminList.html
groupware/src/main/resources/templates/accommodation/list.html

1. 관리자가 예약 상태를 반려처리시 반려사유 적을 수 있도록 버튼 변경 및 모달창 추가
2. 사용자 list.html에 반려사유 목록 출력

[psb] 예약 반려처리 commit

---

groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/resources/templates/include/layout.html

[jji] 결재 알람 기능 마무리(css 수정 필요) commit

[jji] 결재 알람 기능 마무리(css 수정 필요) commit

---

groupware/src/main/java/com/mjc/groupware/chat/config/WebConfig.java
groupware/src/main/java/com/mjc/groupware/chat/controller/ChatAttachController.java
groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/java/com/mjc/groupware/chat/entity/ChatAttach.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatAlarmService.java
groupware/src/main/resources/static/css/ysw.css
groupware/src/main/resources/templates/chat/chat.html
groupware/src/main/resources/templates/include/layout.html

[ysw] 채팅방 클릭 시 이미지 , 파일 조회 + 상세 조회 반영

[ysw] 채팅방 클릭 시 이미지 , 파일 조회 + 상세 조회 반영

---

groupware/src/main/java/com/mjc/groupware/attendance/controller/AttendanceController.java
groupware/src/main/java/com/mjc/groupware/home/comtroller/HomeController.java
groupware/src/main/resources/templates/approval/admin/approvalManagement.html
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/receiveApprovalDetail.html
groupware/src/main/resources/templates/approval/user/sendApprovalDetail.html
groupware/src/main/resources/templates/attendance/admin/annualLeaveManagement.html
groupware/src/main/resources/templates/attendance/user/attendanceInfo.html
groupware/src/main/resources/templates/home.html

[jji] 연차 개수 제한 및 결재상세페이지 파일 다운로드 오류 해결 commit

[jji] 연차 개수 제한 및 결재상세페이지 파일 다운로드 오류 해결 commit

---

groupware/src/main/resources/templates/chat/chat.html

[ysw] 알림 기능 구현 중 commit

---

groupware/src/main/java/com/mjc/groupware/board/controller/BoardController.java
groupware/src/main/java/com/mjc/groupware/board/repository/BoardRepository.java
groupware/src/main/java/com/mjc/groupware/board/service/BoardAttachService.java
groupware/src/main/java/com/mjc/groupware/board/service/BoardService.java
groupware/src/main/java/com/mjc/groupware/reply/controller/ReplyController.java
groupware/src/main/resources/static/css/kdy.css
groupware/src/main/resources/templates/board/create.html
groupware/src/main/resources/templates/board/detail.html
groupware/src/main/resources/templates/board/list.html
groupware/src/main/resources/templates/board/update.html

조회수가 2개씩 늘어남(완료) - 1씩만 올라가게 수정
★ 차트 기능
투표 수정시 모달창 버튼 "추가"가 아니라 "수정"으로 글씨 변경(완료)
create.html(board) - js 코드 수정
일반 게시글만 수정을 할 경우에 투표삭제 버튼을 숨김처리 해줌(일단은 그렇게 해둠)
투표한 게시글은 투표 삭제 버튼이 보이게 해주고, 만약에 투표 삭제을 클릭하면 없어지고, 삭제버튼도 숨김처리하게 해둠
투표 삭제 후 다시 투표 추가 버튼 클릭시 모달창에 입력된 정보들 초기화(완료)
create.html(board) - js 코드 수정
수정,삭제 버튼이 있는데 삭제 버튼을 클릭하고, 투표 추가 버튼을 클릭하면 투표 항목이 그대로 남아있음(초기화)
게시글 상세(투표 텍스트 부분) 결과차트 | 투표하기(투표완료(클릭X)) 투표 마감이 되었을때 투표 완료 버튼은 남게 변경, 결과차트 밑에 "투표 마감되었습니다" 라는 문구가 뜰수있게 설정
결과 차트 부분 = 애니메이션 효과 X.  CSS 디자인쪽 수정,글자수 제한(2자-7자),alert창으로 몇글자 이내로 항목을 입력할수있습니다 라는 문구를 띄워줌,퍼센트 제거해주니까 깔끔하고 보기 좋음
그래프 부분에 마우스 포인터를 갖다대면 익명은 n표, 실명은 [부서]성명으로 보일수있게 해줘야함
실명 = [부서]성명을 3명씩 보일수있게 해주니까 더 깔끔해서 보기 좋아서 바꿈(5명)은 다 짤려서 나오니까 보기가 싫었음

[kdy] 게시판/댓글,대댓글/투표 기능 수정 commit

---

groupware/src/main/java/com/mjc/groupware/approval/controller/ApprovalController.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalAttachService.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalService.java
groupware/src/main/resources/templates/approval/user/createApproval.html
groupware/src/main/resources/templates/approval/user/receiveApprovalDetail.html
groupware/src/main/resources/templates/approval/user/sendApprovalDetail.html

[jji] 전자결재 및 근태관리 에러 수정 commit

[jji] 전자결재 및 근태관리 에러 수정 commit

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationAdminController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/repository/AccommodationReservationRepository.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationReservationService.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationService.java
groupware/src/main/resources/templates/accommodation/adminCreate.html
groupware/src/main/resources/templates/accommodation/adminDetail.html
groupware/src/main/resources/templates/accommodation/adminHome.html
groupware/src/main/resources/templates/accommodation/home.html

[psb] 필터링 commit

---

groupware/src/main/java/com/mjc/groupware/board/controller/BoardAttachController.java
groupware/src/main/java/com/mjc/groupware/board/controller/BoardController.java
groupware/src/main/resources/templates/board/create.html
groupware/src/main/resources/templates/board/detail.html
groupware/src/main/resources/templates/board/list.html
groupware/src/main/resources/templates/board/update.html

첨부파일 수정
게시판 상세 수정
결과차트 버튼 누구나 볼수있게 설정

[kdy] 첨부파일 수정, 게시판 상세 수정

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationAdminController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/AccommodationInfoDto.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/SearchDto.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationService.java
groupware/src/main/resources/templates/accommodation/home.html

[psb] 지역필터링 완료 commit

---

groupware/src/main/java/com/mjc/groupware/approval/dto/ApprovalAlarmDto.java
groupware/src/main/java/com/mjc/groupware/approval/service/ApprovalAlarmService.java
groupware/src/main/java/com/mjc/groupware/attendance/controller/AttendanceController.java
groupware/src/main/java/com/mjc/groupware/attendance/dto/HolidayDto.java
groupware/src/main/java/com/mjc/groupware/attendance/repository/HolidayRepository.java
groupware/src/main/java/com/mjc/groupware/attendance/service/HolidayService.java
groupware/src/main/java/com/mjc/groupware/common/scheduler/RegularEventScheduler.java
groupware/src/main/java/com/mjc/groupware/common/websocket/entity/Alarm.java
groupware/src/main/java/com/mjc/groupware/common/websocket/entity/AlarmMapping.java
groupware/src/main/java/com/mjc/groupware/common/websocket/repository/AlarmMappingRepository.java
groupware/src/main/java/com/mjc/groupware/common/websocket/repository/AlarmRepository.java
groupware/src/main/resources/templates/attendance/admin/annualLeaveManagement.html

[설명 주석 추가 commit]
[휴일 정보 출력, 추가, 수정, 삭제 기능 구현 commit]

[jji]알람 및 알람 매핑 entity 구현 및 데이터베이스 저장 확인 commit

---

groupware/src/main/java/com/mjc/groupware/board/controller/BoardController.java
groupware/src/main/java/com/mjc/groupware/vote/controller/VoteController.java
groupware/src/main/java/com/mjc/groupware/vote/entity/VoteOption.java
groupware/src/main/java/com/mjc/groupware/vote/repository/VoteOptionRepository.java
groupware/src/main/java/com/mjc/groupware/vote/service/VoteService.java
groupware/src/main/resources/templates/board/detail.html

투표에서 수정을 하면 항목이 제거되지 않고, 생성되는거 다시 막아줌

[kdy] 투표에서 수정을 하면 항목이 같이 생성되는거 다시 막아줌

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/AccommodationAdminController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/AccommodationInfoDto.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/PageDto.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/SearchDto.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/AccommodationService.java
groupware/src/main/java/com/mjc/groupware/board/controller/BoardController.java
groupware/src/main/resources/templates/accommodation/adminCreate.html
groupware/src/main/resources/templates/accommodation/adminDetail.html
groupware/src/main/resources/templates/accommodation/adminHome.html
groupware/src/main/resources/templates/accommodation/adminUpdate.html
groupware/src/main/resources/templates/accommodation/home.html

[psb] adminUpdate부분 주소 수정,숙소유형 수정 commit

[psb] adminUpdate부분 주소 수정,숙소유형 수정 commit

---

groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java
groupware/src/main/java/com/mjc/groupware/plan/dto/PlanLogDto.java
groupware/src/main/java/com/mjc/groupware/plan/entity/PlanAlarm.java
groupware/src/main/java/com/mjc/groupware/plan/entity/PlanLog.java
groupware/src/main/java/com/mjc/groupware/plan/repository/PlanLogRepository.java
groupware/src/main/java/com/mjc/groupware/plan/service/PlanService.java
groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/accommodation/adminList.html
groupware/src/main/resources/templates/home.html
groupware/src/main/resources/templates/plan/calendar.html

[psb] 일정 home화면에 출력 및 부서 미배정인 사용자 오류부분 수정

[psb] 일정 home화면에 출력 및 부서 미배정인 사용자 오류부분 수정

---

groupware/src/main/resources/templates/accommodation/adminHome.html
groupware/src/main/resources/templates/accommodation/list.html

[psb] 예약취소 문구 추가 commit

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatAttachController.java
groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatAlarmDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMemberInfoDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatMsgDto.java
groupware/src/main/java/com/mjc/groupware/chat/dto/ChatRoomDto.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatAlarmService.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatMsgService.java
groupware/src/main/java/com/mjc/groupware/chat/service/ChatRoomService.java
groupware/src/main/resources/static/css/ysw.css
groupware/src/main/resources/templates/chat/chat.html
groupware/src/main/resources/templates/include/layout.html

[ysw] 알림 오류 수정(읽음 처리 미포함) + 프로필 이미지 반영 +  1:1채팅 생성 조건 추가 + CSS수정

[ysw] 알림 오류 수정(읽음 처리 미포함) + 프로필 이미지 반영 +  1:1채팅 생성 조건 추가 + CSS수정

---

groupware/src/main/resources/templates/home.html

[psb] home.html 일정 수정 commit

---

groupware/src/main/java/com/mjc/groupware/chat/service/ChatMsgService.java
groupware/src/main/java/com/mjc/groupware/home/comtroller/HomeController.java
groupware/src/main/resources/templates/chat/chat.html
groupware/src/main/resources/templates/home.html
groupware/src/main/resources/templates/include/layout.html

[ysw] 스크롤 수정 + 이미지, 파일 조회 정렬 수정 + 홈 화면 채팅 추가

[ysw] 스크롤 수정 + 이미지, 파일 조회 정렬 수정 + 홈 화면 채팅 추가

---

groupware/src/main/java/com/mjc/groupware/attendance/entity/Attendance.java
groupware/src/main/java/com/mjc/groupware/common/scheduler/RegularEventScheduler.java
groupware/src/main/java/com/mjc/groupware/plan/repository/PlanRepository.java

[jji] 스케줄러로 연차사원 근태이력 저장(날짜만) commit

[jji] 스케줄러로 연차사원 근태이력 저장(날짜만) commit

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/KakaoPayController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/ApproveResponse.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/dto/ReadyResponse.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/KakaoPayService.java
groupware/src/main/java/com/mjc/groupware/common/util/SessionUtils.java
groupware/src/main/resources/templates/accommodation/list.html

[psb] 카카오톡 결제 코드 commit

---

groupware/src/main/java/com/mjc/groupware/board/repository/BoardRepository.java
groupware/src/main/java/com/mjc/groupware/board/service/BoardService.java
groupware/src/main/java/com/mjc/groupware/home/comtroller/HomeController.java
groupware/src/main/resources/templates/home.html
groupware/src/main/resources/templates/include/layout.html

[kdy] 홈화면 수정

---

groupware/src/main/java/com/mjc/groupware/accommodationReservation/controller/KakaoPayController.java
groupware/src/main/java/com/mjc/groupware/accommodationReservation/service/KakaoPayService.java
groupware/src/main/resources/templates/accommodation/orderCompleted.html

[psb] 카카오결제 오류 수정 commit

---

groupware/src/main/resources/templates/home.html

[ysw] 채팅 홈화면 글씨 수정

---

groupware/src/main/resources/templates/error/400.html
groupware/src/main/resources/templates/error/403.html
groupware/src/main/resources/templates/error/404.html
groupware/src/main/resources/templates/error/405.html
groupware/src/main/resources/templates/error/500.html

[ysw] 에러 페이지 반영

---

groupware/src/main/resources/templates/board/create.html
groupware/src/main/resources/templates/board/detail.html
groupware/src/main/resources/templates/board/list.html
groupware/src/main/resources/templates/board/update.html

[kdy] 게시판 alert,confirm창 수정

---

groupware/src/main/resources/templates/home.html

게시글에서는 고정글을 작성하면 고정글만 나오게 되어있는데, 홈화면에서는 고정글이랑 일반글이 같이 생성되서 막아줌

[kdy] 게시글에서 고정글을 작성하면 일반글이랑 홈화면에 같이 생성되는거 막아줌

---

groupware/src/main/java/com/mjc/groupware/board/repository/BoardRepository.java
groupware/src/main/java/com/mjc/groupware/board/service/BoardService.java
groupware/src/main/java/com/mjc/groupware/home/comtroller/HomeController.java

[kdy] 홈화면 자유게시판에서 고정글 1개만 고정 나머지는 일반글로 나올수있게 수정 commit

[kdy] 홈화면 자유게시판에서 고정글 1개만 고정 나머지는 일반글로 나올수있게 수정 commit

---

groupware/src/main/java/com/mjc/groupware/chat/controller/ChatController.java
groupware/src/main/resources/templates/chat/chat.html

[ysw] commit

---

groupware/src/main/java/com/mjc/groupware/plan/controller/PlanController.java

서버쪽에서 실행이 안되서 planController 코드 4줄 삭제

[psb] planController 코드 delete commit

---

groupware/src/main/resources/static/js/custom/calendar.js
groupware/src/main/resources/templates/plan/calendar.html

[psb] 일정등록시 휴가부분 삭제 commit

---

groupware/src/main/java/com/mjc/groupware/member/security/WebSecurityConfig.java

[ysw] test

---

groupware/src/main/java/com/mjc/groupware/common/websocket/WebSocketConfig.java
groupware/src/main/java/com/mjc/groupware/member/security/WebSecurityConfig.java

[ysw] local 웬소캣수정 반영
